import type { ParsedFile } from "./parser";
import JSZip from "jszip";

export interface ExportOptions {
  zipName?: string;           // default: "xevora-project.zip"
  includeReadme?: boolean;    // auto-generate a README.md
}

export async function exportAsZip(
  files: ParsedFile[],
  options: ExportOptions = {}
): Promise<void> {
  const { zipName = "xevora-project.zip", includeReadme = true } = options;

  const zip = new JSZip();

  // Add all files
  for (const file of files) {
    zip.file(file.filename, file.content);
  }

  // Auto-generate README
  if (includeReadme && !files.some((f) => f.filename === "README.md")) {
    zip.file("README.md", generateReadme(files));
  }

  // Generate blob and trigger download
  const blob = await zip.generateAsync({ type: "blob" });
  triggerDownload(blob, zipName);
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.style.display = "none";
  document.body.appendChild(a);
  a.click();

  // Cleanup after download starts
  setTimeout(() => {
    URL.revokeObjectURL(url);
    document.body.removeChild(a);
  }, 1000);
}

function generateReadme(files: ParsedFile[]): string {
  const fileList = files
    .map((f) => `- \`${f.filename}\``)
    .join("\n");

  return `# Xevora AI — Generated Project

Generated by [Xevora AI Vibe Studio](https://github.com/techxsarwar/XEVORA-AI).

## Files

${fileList}

## Usage

Open \`index.html\` in your browser, or serve with any static file server:

\`\`\`bash
npx serve .
\`\`\`

---
*Built with Xevora AI by Sarwar Altaf Dar*
`;
}
